//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRACT.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string _About___ {
            get {
                return ResourceManager.GetString("&About...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string _Copy {
            get {
                return ResourceManager.GetString("&Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string _Edit {
            get {
                return ResourceManager.GetString("&Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string _File {
            get {
                return ResourceManager.GetString("&File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string _Help {
            get {
                return ResourceManager.GetString("&Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string _New {
            get {
                return ResourceManager.GetString("&New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string _Open {
            get {
                return ResourceManager.GetString("&Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string _Options {
            get {
                return ResourceManager.GetString("&Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string _Paste {
            get {
                return ResourceManager.GetString("&Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string _Redo {
            get {
                return ResourceManager.GetString("&Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string _Save {
            get {
                return ResourceManager.GetString("&Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string _Tools {
            get {
                return ResourceManager.GetString("&Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string _Undo {
            get {
                return ResourceManager.GetString("&Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Music.
        /// </summary>
        internal static string Backup_Music {
            get {
                return ResourceManager.GetString("Backup Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating music library files size.
        /// </summary>
        internal static string Calculating_music_library_files_size {
            get {
                return ResourceManager.GetString("Calculating music library files size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        internal static string Cancelled_ {
            get {
                return ResourceManager.GetString("Cancelled!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking files stored in.
        /// </summary>
        internal static string Checking_files_stored_in {
            get {
                return ResourceManager.GetString("Checking files stored in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing program.
        /// </summary>
        internal static string Closing_program {
            get {
                return ResourceManager.GetString("Closing program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string Cu_t {
            get {
                return ResourceManager.GetString("Cu&t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        internal static string Duplicates {
            get {
                return ResourceManager.GetString("Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string E_xit {
            get {
                return ResourceManager.GetString("E&xit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Error_ {
            get {
                return ResourceManager.GetString("Error:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string File_not_found {
            get {
                return ResourceManager.GetString("File not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) could not be copied.
        /// </summary>
        internal static string file_s__could_not_be_copied {
            get {
                return ResourceManager.GetString("file(s) could not be copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        internal static string Finished_ {
            get {
                return ResourceManager.GetString("Finished!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate M3U8 Playlists.
        /// </summary>
        internal static string Generate_M3U8_Playlists {
            get {
                return ResourceManager.GetString("Generate M3U8 Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Scripts.
        /// </summary>
        internal static string Generate_Scripts {
            get {
                return ResourceManager.GetString("Generate Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impossible to copy.
        /// </summary>
        internal static string impossible_to_copy {
            get {
                return ResourceManager.GetString("impossible to copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to start processing:.
        /// </summary>
        internal static string Impossible_to_start_processing_ {
            get {
                return ResourceManager.GetString("Impossible to start processing:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music files processed.
        /// </summary>
        internal static string music_files_processed {
            get {
                return ResourceManager.GetString("music files processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphans.
        /// </summary>
        internal static string Orphans {
            get {
                return ResourceManager.GetString("Orphans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists loaded!.
        /// </summary>
        internal static string Playlists_loaded_ {
            get {
                return ResourceManager.GetString("Playlists loaded!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view.
        /// </summary>
        internal static string Print_Pre_view {
            get {
                return ResourceManager.GetString("Print Pre&view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Log.
        /// </summary>
        internal static string Process_log {
            get {
                return ResourceManager.GetString("Process log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing duplicates....
        /// </summary>
        internal static string Processing_duplicates___ {
            get {
                return ResourceManager.GetString("Processing duplicates...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing missing tracks....
        /// </summary>
        internal static string Processing_missing_tracks___ {
            get {
                return ResourceManager.GetString("Processing missing tracks...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing orphans....
        /// </summary>
        internal static string Processing_orphans___ {
            get {
                return ResourceManager.GetString("Processing orphans...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing unanalyzed tracks....
        /// </summary>
        internal static string Processing_unanalyzed_tracks___ {
            get {
                return ResourceManager.GetString("Processing unanalyzed tracks...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing unreferenced files....
        /// </summary>
        internal static string Processing_unreferenced_files___ {
            get {
                return ResourceManager.GetString("Processing unreferenced files...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing untagged tracks....
        /// </summary>
        internal static string Processing_untagged_tracks___ {
            get {
                return ResourceManager.GetString("Processing untagged tracks...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        internal static string Save__As {
            get {
                return ResourceManager.GetString("Save &As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string Select__All {
            get {
                return ResourceManager.GetString("Select &All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Statistics.
        /// </summary>
        internal static string Show_Statistics {
            get {
                return ResourceManager.GetString("Show Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting music files copy from.
        /// </summary>
        internal static string Starting_music_files_copy_from {
            get {
                return ResourceManager.GetString("Starting music files copy from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up....
        /// </summary>
        internal static string Starting_up___ {
            get {
                return ResourceManager.GetString("Starting up...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could take a long time. Would you like to overwrite the existing files ?.
        /// </summary>
        internal static string This_could_take_a_long_time__Would_you_like_to_overwrite_the_existing_files__ {
            get {
                return ResourceManager.GetString("This could take a long time. Would you like to overwrite the existing files ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this may take a while....
        /// </summary>
        internal static string this_may_take_a_while___ {
            get {
                return ResourceManager.GetString("this may take a while...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing.
        /// </summary>
        internal static string tooltip_MainForm_btnProcess {
            get {
                return ResourceManager.GetString("tooltip.MainForm.btnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates are track with the same artist and title.
        /// </summary>
        internal static string tooltip_MainForm_chkDuplicates {
            get {
                return ResourceManager.GetString("tooltip.MainForm.chkDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks that can&apos;t be found on disk.
        /// </summary>
        internal static string tooltip_MainForm_chkMissing {
            get {
                return ResourceManager.GetString("tooltip.MainForm.chkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphans are tracks not listed in any playlist.
        /// </summary>
        internal static string tooltip_MainForm_chkOrphans {
            get {
                return ResourceManager.GetString("tooltip.MainForm.chkOrphans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks that were not properly prepared and analyzed.
        /// </summary>
        internal static string tooltip_MainForm_chkUnanalyzed {
            get {
                return ResourceManager.GetString("tooltip.MainForm.chkUnanalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks from the Music folder that have not been imported in the library.
        /// </summary>
        internal static string tooltip_MainForm_chkUnreferenced {
            get {
                return ResourceManager.GetString("tooltip.MainForm.chkUnreferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks without metadata (ID3).
        /// </summary>
        internal static string tooltip_MainForm_chkUntagged {
            get {
                return ResourceManager.GetString("tooltip.MainForm.chkUntagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process progression.
        /// </summary>
        internal static string tooltip_MainForm_progBar {
            get {
                return ResourceManager.GetString("tooltip.MainForm.progBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size:.
        /// </summary>
        internal static string Total_size_ {
            get {
                return ResourceManager.GetString("Total size:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track(s) loaded!.
        /// </summary>
        internal static string track_s__loaded_ {
            get {
                return ResourceManager.GetString("track(s) loaded!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unanalyzed.
        /// </summary>
        internal static string Unanalyzed {
            get {
                return ResourceManager.GetString("Unanalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreferenced.
        /// </summary>
        internal static string Unreferenced {
            get {
                return ResourceManager.GetString("Unreferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untagged.
        /// </summary>
        internal static string Untagged {
            get {
                return ResourceManager.GetString("Untagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to copy.
        /// </summary>
        internal static string You_re_about_to_copy {
            get {
                return ResourceManager.GetString("You\'re about to copy", resourceCulture);
            }
        }
    }
}
